// Report
export const SET_PAGE = "SET_PAGE";
export const SET_LIMIT = "SET_LIMIT";
export const SET_SEARCH_TERM = "SET_SEARCH_TERM";
export const SET_SEARCH_COL = "SET_SEARCH_COL";
export const SET_FILTERS = "SET_FILTERS";

// Record
export const SET_SELECTED_CUSTOMER = "SET_SELECTED_CUSTOMER";
export const SET_SELECTED_BRANCH = "SET_SELECTED_BRANCH";
export const SET_SELECTED_SUPPLIER = "SET_SELECTED_SUPPLIER";
export const SET_SELECTED_MODEL = "SET_SELECTED_MODEL";
export const SET_SELECTED_STAFF = "SET_SELECTED_STAFF";
export const RESET_RECORD_DATA = "RESET_RECORD_DATA";

// Withdrawal
export const SET_CURRENT_WITHDRAWAL = "SET_CURRENT_WITHDRAWAL";
export const SET_ITEMS = "SET_ITEMS";

// Error
export const SET_ERROR = "SET_ERROR";